# HW2: Publish a Web Page with GitHub Pages

**COMPSS 211A · Fall 2026 · Due Sunday, October 4 at 11:59 p.m. Pacific**

Publish a guide to Berkeley places and services, then change what it shows by editing its CSV data in this notebook.

We supply a working website with eight resources. You will improve one existing entry, add one resource, and publish a guide with nine entries. You will also write a heading and introduction for your readers.

**The workflow:** edit data in Jupyter → save the CSV → inspect, commit, and push in GitHub Desktop → check the website.

GitHub builds the webpage from the CSV and our supplied layout. You only need to understand the short pandas steps below. No HTML, website-generation functions, or Git commands are required.

Submit this completed notebook with your repository link, website link, three commit IDs and messages, and a short explanation.

## 1. Create your website repository

1. Open the [HW2 starter template](https://github.com/macss-berkeley/hw2-hidden-berkeley-template). Choose **Use this template → Create a new repository**. Select your account, name the repository `hidden-berkeley`, and choose **Public**. If you already used that name for earlier practice, choose `hidden-berkeley-hw2`.
2. In GitHub Desktop, choose **File → Clone Repository → URL** and paste the URL of **your new repository**. Clone it outside your course repository.
3. Open that complete folder in VS Code. Open the `hw2_hidden_berkeley.ipynb` inside it. Work in this copy throughout the assignment. If you are reading the copy in the course repository, switch to your new repository now.
4. Select the course Python environment you used in Weeks 1–2 as the notebook kernel. If it is not listed, select the Python interpreter in the course repository's `.venv` folder: `.venv/bin/python` on macOS/Linux or `.venv\Scripts\python.exe` on Windows. See the [course setup guide](https://github.com/macss-berkeley/compss-211a/blob/main/SETUP.md) if you have not completed that setup.

A template gives you a new repository containing the starter files. It already exists on GitHub, so subsequent uploads use **Push origin** in Desktop.

| File | Your work |
| --- | --- |
| `docs/_data/locations.csv` | Edit this data through the notebook. Each row becomes one website entry. |
| `docs/index.md` | Edit the heading and introduction near the top. |
| `README.md` | Explain your guide, source, and website checks. |
| This notebook | Save your data-editing code, outputs, and evidence. |

The supplied layout and configuration files need no edits.

## 2. Publish the starter website

Do this before changing the data so you can see the starting point.

1. Open **your repository** on GitHub. Go to **Settings → Pages**.
2. Under **Build and deployment → Source**, choose **Deploy from a branch**. Select **main**, choose **/docs**, and select **Save**.
3. Wait for the deployment to finish. The repository's **Actions** tab shows its progress. Open the website address shown in Pages settings. The first build can take a few minutes.
4. Find Morrison Library on the page. Later you will compare the page with its row in the CSV.

Your repository URL (`github.com/YOUR-USERNAME/hidden-berkeley`) shows the files and history. Your website URL (`YOUR-USERNAME.github.io/hidden-berkeley/`) opens the guide. Record your actual URLs in section 6.

In `docs/index.md`, change `# Hidden Berkeley` to your chosen heading and replace the introduction with two sentences for someone new to Berkeley. Keep the opening `---` block and the supplied loop below the introduction.

**Commit 1:** save the file. In Desktop, select your HW2 repository, inspect the `docs/index.md` diff under **Changes**, and check only intended files. Enter a descriptive **Summary**, select **Commit to main**, then **Push origin**. After the build finishes, check the heading and introduction on your website.

## 3. Read the website's CSV

The cell below loads the actual CSV used by the website. `index_col="location_id"` uses each resource's identifier as its row label, so we can select a row with `.loc["HB03"]`.

The columns describe the resource's name, category, area, access information, and official webpage. Find Morrison Library in the displayed table and compare it with the website.

Run the notebook from your HW2 repository folder. If the CSV is not found, check that you opened that complete folder and its notebook in VS Code.

In [1]:
import pandas as pd

csv_path = "docs/_data/locations.csv"
locations = pd.read_csv(csv_path, index_col="location_id")
locations

,name,category,area,access_note,source_url
location_id,,,,,
HB01,D-Lab,methods support,Social Sciences Building,Check the official site for current access det...,https://dlab.berkeley.edu/
HB02,BAMPFA Film Library and Study Center,media research,Downtown Berkeley,Confirm appointments and access on the officia...,https://bampfa.org/
HB03,Morrison Library,quiet reading,Doe Library,Library access policies can change,https://www.lib.berkeley.edu/
HB04,Jacobs Institute Makerspace,prototyping,North campus,Training may be required before equipment use,https://jacobsinstitute.berkeley.edu/
HB05,Basic Needs Center,student support,UC Berkeley,Use official pages for eligibility and hours,https://basicneeds.berkeley.edu/
HB06,Disabled Students' Program,access support,UC Berkeley,Do not publish private accommodation information,https://dsp.berkeley.edu/
HB07,Berkeley Art Museum and Pacific Film Archive,arts and archives,Downtown Berkeley,Admission and hours vary,https://bampfa.org/
HB08,UC Botanical Garden,field observation,Strawberry Canyon,Check current reservations and transit,https://botanicalgarden.berkeley.edu/

## 4. Improve one entry and add a resource

Open an existing resource's official webpage. Improve its access note with a specific, useful detail you can verify there. For example, clarify who can use it or where to check visiting arrangements. Replace the two placeholder strings below; keep the identifier of a resource already in the table.

`.loc[row_label, column_name]` selects one cell. Assigning a string changes that cell in the DataFrame. The last line displays your updated row. This has not saved the CSV yet.

In [2]:
existing_id = "HB03"  # Editing the Morrison Library.
locations.loc[existing_id, "access_note"] = "Morrison is generally open between 10:00AM and 5:00PM on weekdays. Please check the official website for the most up to date information." 
locations.loc[existing_id, "source_url"] = "https://www.lib.berkeley.edu/visit/morrison"
locations.loc[existing_id]

name                                            Morrison Library
category                                           quiet reading
area                                                 Doe Library
access_note    Morrison is generally open between 10:00AM and...
source_url           https://www.lib.berkeley.edu/visit/morrison
Name: HB03, dtype: object

Now choose one Berkeley place or service that is not already listed. Check its official webpage and replace every placeholder in this dictionary. Use public information and retain all eight original resources.

The dictionary keys match the CSV columns. `.loc["HB09"] = new_resource` puts those values in a row labeled `HB09`. Running it again replaces that same row, so rerunning the notebook does not add duplicates.

In [3]:
new_resource = {
    "name": "UC Berkeley Career Center",
    "category": "student support",
    "area": "UC Berkeley",
    "access_note": "The Career Center offers career planning essentials, events and workshops, career counseling appointments, job and internship search resources and support, and planning for graduate and professional school to undergraduates, graduate students, and alumni.",
    "source_url": "https://career.berkeley.edu/",
}

locations.loc["HB09"] = new_resource
locations

,name,category,area,access_note,source_url
location_id,,,,,
HB01,D-Lab,methods support,Social Sciences Building,Check the official site for current access det...,https://dlab.berkeley.edu/
HB02,BAMPFA Film Library and Study Center,media research,Downtown Berkeley,Confirm appointments and access on the officia...,https://bampfa.org/
HB03,Morrison Library,quiet reading,Doe Library,Morrison is generally open between 10:00AM and...,https://www.lib.berkeley.edu/visit/morrison
HB04,Jacobs Institute Makerspace,prototyping,North campus,Training may be required before equipment use,https://jacobsinstitute.berkeley.edu/
HB05,Basic Needs Center,student support,UC Berkeley,Use official pages for eligibility and hours,https://basicneeds.berkeley.edu/
HB06,Disabled Students' Program,access support,UC Berkeley,Do not publish private accommodation information,https://dsp.berkeley.edu/
HB07,Berkeley Art Museum and Pacific Film Archive,arts and archives,Downtown Berkeley,Admission and hours vary,https://bampfa.org/
HB08,UC Botanical Garden,field observation,Strawberry Canyon,Check current reservations and transit,https://botanicalgarden.berkeley.edu/
HB09,UC Berkeley Career Center,student support,UC Berkeley,The Career Center offers career planning essen...,https://career.berkeley.edu/

### Save your data changes

Check the table above before saving: nine rows, all eight original identifiers (`HB01`–`HB08`), your improved entry, and your new `HB09` entry. Replace every placeholder and make sure both source links open the official pages you checked.

The first line below writes the DataFrame back to the website's CSV, including the `location_id` row labels. The second line reads the saved file again so you can verify what is on disk. Changing a DataFrame in memory does not update the file until you call `to_csv`.

Do not use `index=False` here: the website CSV needs those identifiers.

In [4]:
locations.to_csv(csv_path, index_label="location_id")
pd.read_csv(csv_path)

,location_id,name,category,area,access_note,source_url
0,HB01,D-Lab,methods support,Social Sciences Building,Check the official site for current access det...,https://dlab.berkeley.edu/
1,HB02,BAMPFA Film Library and Study Center,media research,Downtown Berkeley,Confirm appointments and access on the officia...,https://bampfa.org/
2,HB03,Morrison Library,quiet reading,Doe Library,Morrison is generally open between 10:00AM and...,https://www.lib.berkeley.edu/visit/morrison
3,HB04,Jacobs Institute Makerspace,prototyping,North campus,Training may be required before equipment use,https://jacobsinstitute.berkeley.edu/
4,HB05,Basic Needs Center,student support,UC Berkeley,Use official pages for eligibility and hours,https://basicneeds.berkeley.edu/
5,HB06,Disabled Students' Program,access support,UC Berkeley,Do not publish private accommodation information,https://dsp.berkeley.edu/
6,HB07,Berkeley Art Museum and Pacific Film Archive,arts and archives,Downtown Berkeley,Admission and hours vary,https://bampfa.org/
7,HB08,UC Botanical Garden,field observation,Strawberry Canyon,Check current reservations and transit,https://botanicalgarden.berkeley.edu/
8,HB09,UC Berkeley Career Center,student support,UC Berkeley,The Career Center offers career planning essen...,https://career.berkeley.edu/

## 5. Push the data and check the website

**Commit 2:** save this notebook. In Desktop, inspect the CSV diff. Find the existing entry you changed and the new `HB09` row. Commit the CSV and notebook with a message describing the data changes, then **Push origin**.

Open the CSV on GitHub and check that the edits arrived. Wait for the Pages build to finish, then open your website in a private browser window. Check that:

- All nine resources appear, including the one you added.
- The improved access note matches the CSV.
- Your new resource's details match the CSV, and the official links work.
- Your heading and introduction appear.

The supplied loop in `docs/index.md` tells GitHub's website builder to display each CSV row. GitHub rebuilds the page after a push. You do not copy rows into Markdown or run website-building code in Jupyter.

If GitHub has the updated CSV but the website is old, check the latest deployment in **Actions** and refresh after it finishes.

Edit the **Purpose and sources** and **Website checks** sections of `README.md`. State who the guide is for, name and link your added resource, and describe what you actually checked. Commit and push these changes as **commit 3**. The template's initial commit does not count toward your three commits.

## 6. Record your work

Fill in the URLs below. In Desktop's **History**, select each of your three commits and copy its commit ID (hash/SHA) and message into `GIT_LOG`, one per line. Short or full IDs are fine. Use your actual history; no terminal output is needed.

In [6]:
REPOSITORY_URL = "https://github.com/ajweijiang/hidden-berkeley.git"
PAGES_URL = "https://ajweijiang.github.io/hidden-berkeley/"
GIT_LOG = """
32b2fc0da05a8ec7c51fe2b7f72aacefb9f38fa6 - Updates to Index.md, I changed the heading of the document to make it more approachable to readers. I also made a peppier description for the document.
88a943c5b7e3ca63343862ec51f1bd35d680a93f - Changed Morrison Library item and Locations.csv, I updated the Morrison Library's access note to be a bit more descriptive and changed the source link to the specific library's website, not just UC Berkeley overall. I also added the Career Center as a Berkeley resource with all the relevant details. including the name, category, area, access note, and official source.
abf1afa97a73a416204ba5535389b927764540ec - Commit 3: Updated README.md, I updated the README file to replace the template paragraphs under Purpose and sources and Website checks
"""

### Your explanation

This is my explanation on how I added the 9th resources step by step through the different components of this repo. First, in Step 3, we saved the file path for locations.csv into the object csv_path. We then used the pandas pd.read_csv function to read in locations.csv (using the csv_path object we just made) to a pandas DataFrame called locations. We used the index_col = "location_id" to make sure each resource's identifier is its row label which we can now use to select with .loc.

Next, we created a new dictionary called new_resource with the keys following the column names of the location.csv format (name, category, area, access_note, and source_url). We added the values with corresponding text for those columns. Next, we created a new row "HB09", using locations.loc["HB09"], and assigned it the new_resource dictionary. Now the "locations" dataframe has a new row with our 9th resource and corresponding information. The locations DataFrame is updated, but the original csv we read from to create locations doesn't change until we rewrite it with the changes to the csv. We do that by using the pandas .to_CSV method, which uses locations DataFrame and writes that onto the csv with the file path stored in the object csv_path, using the "location_id" as the index. Now that locations.csv has been updated to have the new resource we created and our hw2_hidden_berkeley.ipynb is also saved, we can submit our second commit. We can then "Push origin" which will change the actual GitHub repo. Once the changes are loaded, we can see the updated website has the 9th resource that we added. You can use the source link like all the other resources.

To feed two birds with one crumb for this assignment and the AI Journal, I used Gemini to figure out how to use the compss-211a environment / python kernel in this separate repo. I asked for the steps to install the course envrionment given the error I received. Gemini let me know the error I was receiving was because the template repo for this assignment did not have the pyproject.toml file and I needed to run it from my compss-211a repo. I followed the instructions from Gemini, and adapted the instructions to what I needed (ie. Gemini did not know the file paths to the compss-211a directory, so I had to edit those file paths). I prompted it again when i got a "split flag" and an unclosed double quote which was preventing me from running a line in the CLI. Eventually, I was able to get the compss 211a kernel to work in this repo.

## Submit

1. Fill in the links, commit evidence, and explanation above. Remove all `REPLACE` placeholders from your data-editing cells.
2. Restart the kernel and run the notebook from top to bottom. It should still show nine resources: assigning `HB09` again updates that row. Check the saved CSV output.
3. Save the completed notebook. Commit and push any remaining notebook or CSV changes. Extra commits are fine; the three evidence commits can remain the earlier ones.
4. Check the finished website once more after the final build. Save a copy of the completed notebook as `lastname_firstname_hw2.ipynb` and upload that file to bCourses. Keep the notebook in your repository as well. Submit only the `.ipynb`; the links inside it lead to your repository and website.

**AI and collaboration:** Please don't use AI to perform or fabricate the required repository workflow. Complete and explain your own work. Use public resource information and cite the official pages you checked. Disclose any permitted help in your response.

References: [GitHub Pages publishing settings](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site), [GitHub Desktop history](https://docs.github.com/en/desktop/making-changes-in-a-branch/viewing-the-branch-history-in-github-desktop).